on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello to the person
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action 
        id: script
        shell: powershell
        run: |-
          dir        
           ./.github/script.ps1
           
        write-outpt "Hello Script sucess"
